### ISSUE TITLE
Doesn't work with Neovim

### ISSUE THREAD

**Issue by DonnieWest** [extr0py/vim-node-plugins#1]
Neovim doesn't support `clientserver` natively and so doesn't work with this plugin. It appears that there's a plugin you can use to restore this functionality [here](https://github.com/mhinz/neovim-remote) but it doesn't seem to be picked up by vim-node-plugins

**Comment by bryphe** [comment]
Thanks Donnie! Unfortunately I haven't used NeoVim yet (although it looks very promising). Appreciate you sharing the neovim-remote plugin and checking out this project. I logged a couple of additional issues - #19 is another potential fix, the `clientserver` option can potentially be replaced with the job control functionality in NeoVim and now Vim. I also added some info in the readme for now.
